defaults:
  - method: stateless_ppo
  - _self_

paths:
  met_model_path: varma_ecoli_shikki # Metabolic model being analyzed. All data are loaded accordingly from the folder '/Models' in supplementary data
  output_dir: /scratch/izar/cizinsky/rl-for-kinetics/output


constraints:
  ## Custom constraints
  # Minimum value of generated Kms = exp(-25)
  min_km: -25 
  # Maximum value of generated Kms = exp(3)
  max_km: 3

  # Index of the steady state to generate kinetic models around (there are 5000 steady states in the data provided)
  ss_idx: 1712

reward:
  # Desired optimisation objective ( Flag 0 - Push for max incidince of valid models; Flag 1 - Push for fastest dynamic possible)
  flag: 1
  # Number of fastest eigenvalues to consider when Flag = 1
  n_consider: 10 
  # eigenvalue partition between valid and invalid models
  eig_partition: -2.5


# Just to let Hydra know where to save the config file
hydra:
  run:
    dir: ${paths.output_dir}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  job:
    chdir: False