defaults:
  - method: refinement_ppo
  - lr_scheduler: cosine
  - _self_

seed: 42
device: cuda
launch_cmd: null # will be set at runtime dynamically

# for now ignore, we don't use wandb yet
logger:
  project: rl-renaissance
  entity: ludekcizinsky
  tags: [baseline]


paths:
  names_km: data/varma_ecoli_shikki/parameter_names_km_fdp1.pkl
  output_dir: /home/renaissance/output 
  met_model_name: varma_ecoli_shikki

constraints:
  # minimum value of generated Kms = exp(-25)
  min_km: -25 
  # maximum value of generated Kms = exp(3)
  max_km: 3

  # index of the steady state to generate kinetic models around (there are 5000 steady states in the data provided)
  ss_idx: 1712

reward:
  # eigenvalue partition between valid and invalid models
  eig_partition: -2.5
  intermediate_steps_weight: 1.0

env:
  # Initial mean and std the normal distribution for p0
  p0_init_mean: 0
  p0_init_std: 1
  # Total number of kinetic parameters
  p_size: 384 
  # We update next state as x_new = x + action * action_scale
  action_scale: 1.0

training:
  num_episodes: 100
  max_steps_per_episode: 50
  batch_size: 25
  num_epochs: 10
  max_grad_norm: 0.5
  save_trained_models: true
  # number of samples to get the end of the final episode to estimate the reward of the final action
  # 1 = no sampling -> baseline
  n_dist_samples: 1 


# Just to let Hydra know where to save the config file
hydra:
  run:
    dir: ${paths.output_dir}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  job:
    chdir: False